spring.application.name=sip

logging.level.guru.springframework=debug

spring.flyway.enabled=false

spring.docker.compose.enabled=true

jwtSecretString=2VzfM0jJwwih787dqE4Zm3cHZXzW3CL4yuZh6BsrgHVtS0gQ6tWcMxKzaYSHFKGEWx

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=./src/main/resources/static
#file.upload-dir=/home/sgp2/sip/uploads

#production
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/sip
spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql

