CREATE TABLE detidos (
    id BIGSERIAL PRIMARY KEY,
    numero_processo VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    nome_pai VARCHAR(255),
    nome_mae VARCHAR(255),
    data_nascimento DATE,
    naturalidade VARCHAR(255),
    profissao VARCHAR(255),
    numero_bi VARCHAR(255),
    data_emissao_bi DATE,
    local_emissao_bi VARCHAR(255),
    telefone VARCHAR(255),
    endereco VARCHAR(255),
    estado_civil VARCHAR(255),
    idade INTEGER,
    sexo VARCHAR(50),
    estado_detencao VARCHAR(50),
    data_detencao TIMESTAMP WITHOUT TIME ZONE,
    local_detencao VARCHAR(255),
    motivo_detencao TEXT,
    observacoes TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
